import { ExperimentalFeature } from "./ExperimentalFeature";

export interface Features {
    activity_service_read: boolean
    activity_service_write: boolean
    adblock_test: boolean
    ads_auction: boolean
    ads_auto_extend: boolean
    ads_auto_refund: boolean
    adserver_reporting: boolean
    adzerk_do_not_track: boolean
    adzerk_reporting_2: boolean
    block_user_by_report: boolean
    default_srs_holdout: ExperimentalFeature
    do_not_track: boolean
    eu_cookie_policy: boolean
    expando_events: boolean
    force_https: boolean
    geopopular: boolean
    geopopular_au_holdout: ExperimentalFeature
    geopopular_ca_holdout: ExperimentalFeature
    geopopular_mx_holdout: ExperimentalFeature
    geopopular_tw_holdout: ExperimentalFeature
    give_hsts_grants: boolean
    https_redirect: boolean
    inbox_push: boolean
    inject_new: ExperimentalFeature
    interest_targeting: boolean
    legacy_search_pref: boolean
    listing_service_rampup: boolean
    live_happening_now: boolean
    moat_tracking: boolean
    mobile_native_banner: boolean
    mobile_web_targeting: boolean
    mweb_xpromo_ad_loading_ios: ExperimentalFeature
    mweb_xpromo_interstitial_comments_android: boolean
    mweb_xpromo_interstitial_comments_ios: boolean
    mweb_xpromo_modal_listing_click_daily_dismissible_android: boolean
    mweb_xpromo_modal_listing_click_daily_dismissible_ios: boolean
    new_ads_styles: ExperimentalFeature
    new_loggedin_cache_policy: boolean
    new_overview: boolean
    new_report_dialog: boolean
    new_report_flow: boolean
    orangereds_as_emails: boolean
    outbound_clicktracking: boolean
    pause_ads: boolean
    personalization_prefs: boolean
    post_embed: boolean
    post_to_profile_beta: boolean
    programmatic_ads: boolean
    screenview_events: boolean
    scroll_events: boolean
    search_dark_traffic: boolean
    search_public_traffic: ExperimentalFeature
    show_amp_link: boolean
    show_recommended_link: boolean
    show_user_sr_name: boolean
    subreddit_rules: boolean
    upgrade_cookies: boolean
    users_listing: boolean
    whitelisted_pms: boolean
}